### ISSUE TITLE
Digital Twin Manager : Deletion of Asset type and Custom property, which is being used in Asset is allowed.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#1]
In the Asset configuration section below scenarios are allowed, which should not be allowed or user has to be notified regarding the same :

1. Since the same assets and devices can be assigned to different hierarchies/ assets, deletion of these asset or devices from one asset/ hierarchy will affect the other assets/ hierarchy. And the user is not notified about the same.

2. Deletion of an asset type, used in an existing asset is allowed, which is wrong. No user notification received.

3. Deletion of an asset property, being used in an asset type is allowed, which is wrong.

User is not notified about the same.

**Comment by spau6** [comment]
Refer https://itrac.eur.ad.sag/browse/CTM-100 for details
