### ISSUE TITLE
DTM : Validation issues observed in DTM application

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#10]
In DTM application, the below validation issues are observed :

1. In Asset types page, when creating an asset type for "description" field, we can have an upper limit on the maximum characters allowed. This limit can be based on the total length of text displayed when user hovers over the description tab and the maximum text that can be displayed in the hover pop up.
2. When creating an asset type, user has an option to create a custom property field as well. When clicked on create new custom property option, Save button is getting enabled even though required field is empty. 
3. Currently in Asset type page, the confirmation pop up and the success notification on deleting an asset type is different when we delete the asset type via check box and via delete icon. Uniformity has to be maintained.
4. When creating a new asset type, In the notification pop up for Asset types, the key is being used instead of label. 
5. When creating an asset, the validation message displayed is blank, incase it violates the rules mentioned in Custom property. Validation messag has to be displayed.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
