### ISSUE TITLE
DTM: Issues observed in edit property window in subassets page.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#11]
1) Once the asset is created, later if user try to modify the custom property value, and if there is validation error, then the message is not displayed. It displays an empty validation.

2) The cancel option for properties is not working as expected. Edit the custom property and change the custom value and click cancel. Value does not get saved but when clicked on edit again, it shows the modified unsaved value which is incorrect.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
