### ISSUE TITLE
DTM : Same device can be used in multiple hierarchies, which should not be allowed.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#12]
Currently in DTM application the below issues are observed with respect to hierarchy creation and hierarchy structure :

1. Adding same device for different assets should be restricted. User is able to assign the same device to multiple Assets, which is not logical. This should be restricted.

2. Moving an asset outside it's parent should be restricted. Currently user can move an asset outside the parent and place it in a totally different asset hierarchy, which should be restricted. 
Eg : User can move the printer asset from under a Building and place it in Production line which is not relevant/ logical.

      3.  When user tries to move an asset, it is observed that alert popup is getting displayed. Currently the following message is getting displayed on the popup "Do you want to move the group?", this has to be changed like "Do you want to move the asset?".

      4. A generic isseue observed throughou the application is that, user can create duplicate labels / names or names with whitespaces only. Both should be restricted.

**Comment by pavanshivajirao** [comment]
Working as per the design.
