### ISSUE TITLE
No properties of a subasset are displayed

### ISSUE THREAD

**Issue by sagjoin** [SoftwareAG/cumulocity-digital-twin-manager#14]
When adding a subasset to an asset you can navigate to the asset and see its properties (with the bug of not having the labels that is already reported) but if you click on a subasset you only see the devices assigned and no the properties of the subasset.

I think is a bug but i cannot label the issue.

**Comment by GalaxyJadar** [comment]
Fix (i.e., Issue: Properties would show without labels in the current version ) is available in the latest uploaded DTM version
