### ISSUE TITLE
DTM: Suggestion_Not show groups in Digital Twin

### ISSUE THREAD

**Issue by sagjoin** [SoftwareAG/cumulocity-digital-twin-manager#15]
As a suggestion, when you are using Digital Twin Manager in a tenant that already has some folders, the folders are shown in the DTM and messes up the assets configured through DTM and the older assets. There should be an option to hide the folders that doesn't have an asset type defined in DTM

**Comment by carlosceia** [comment]
that was the initial idea: to have 2 separate hierarchies, one with the current groups structure, and another just with the asset hierarchies

**Comment by pavanshivajirao** [comment]
Suggestion is considered and is in road map of DTM now. So closing as of now.
