### ISSUE TITLE
Custom navigator logo is not displayed

### ISSUE THREAD

**Issue by scfx** [SoftwareAG/cumulocity-digital-twin-manager#16]
The navigator logo will not be displayed, if the DTM is used with a custom branding. (v. 1014.0.7)

**Comment by CGuether** [comment]
Logo in left navigation menu is meant.

On dev environment, the logo from defined in a custom branding can be seen. Needs to be checked if this has already been fixed:

![image](https://user-images.githubusercontent.com/57527184/178664268-0839b410-fe23-4d25-992d-ab1ac7f9d824.png)

**Comment by pavanshivajirao** [comment]
Working as expected as specified by Christian. Hence closing this issue.
