### ISSUE TITLE
Can not open in Safari

### ISSUE THREAD

**Issue by zhong-ys** [SoftwareAG/cumulocity-digital-twin-manager#17]
Steps to reproduce:
- Download latest version of DTM from https://github.com/SoftwareAG/cumulocity-digital-twin-manager/releases
- Open Safari, Go to administration > Eco System > Upload Web application
- Upload works fine, a success message is shown
-  =>However, opening the application does not work, there is an endless loading loop

Note: also re-login does not help. In other browsers it works, seems to be Safari related

**Comment by CGuether** [comment]
Safari officially isn't supported by Cumulocity IoT, which is stated in the [documentation](https://www.cumulocity.com/guides/users-guide/getting-started/#supported-browsers):

> Supported browsers in this version are:
Microsoft Edge (latest Chromium-based version)
Mozilla Firefox (latest Extended Support Release)
Google Chrome
Internet Explorer 11

Safari is only supported by Cumulocity IoT on mobile devices:
