### ISSUE TITLE
Switching between two complex properties will show an empty property in the property library.

### ISSUE THREAD

**Issue by scfx** [SoftwareAG/cumulocity-digital-twin-manager#18]
Switching between two complex properties in the property library without clicking on cancel in-between will display an empty property. (v.1014.0.7)
![image](https://user-images.githubusercontent.com/93245336/178275595-66a9f6ff-aa6c-4a7d-9960-f1f9c11ae98b.png)

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
