### ISSUE TITLE
UI not loading after deployment

### ISSUE THREAD

**Issue by mstoffel-sag** [SoftwareAG/cumulocity-digital-twin-manager#19]
After I deployed the webapplication zip file and selected Digital Twin Manager in the app switcher the App is not loading. I only see the turning wheel.

I'm on eu-latest.cumulocity.com

JS console says:

[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (3119.42aad4d6562079f548eb.js:1)
[Error] Unhandled Promise Rejection: ChunkLoadError: Loading chunk 3119 failed.
(missing: https://mstoffel.eu-latest.cumulocity.com/apps/digital-twin-manager/3119.42aad4d6562079f548eb.js)
	generatorResume (bootstrap.53ce2fb8f940af0e7d0a.js:2:109177)
	a (bootstrap.53ce2fb8f940af0e7d0a.js:2:4834)
	promiseReactionJob

**Comment by srinath0707** [comment]
Hi,

Thank you for bringing this to our notice. Can you please share more details like from where you downloaded the DTM artifact( path to the location) and few screenshots showing the steps you tried. This will be very helpful to resolve the issue.

**Comment by mstoffel-sag** [comment]
Hi,

I just downloaded the as documented in the readme from the release section:

https://github.com/SoftwareAG/cumulocity-digital-twin-manager/releases/download/1014.0.0/digital-twin-manager.zip

then followed the instructions. I can show you also on my system if your want to.



Regards,

Marco Stoffel

**Comment by srinath0707** [comment]
Hi Marco,

Please get in touch with me via teams. I will look into the issue.

**Comment by srinath0707** [comment]
Supported browsers in this version are:
Microsoft Edge (latest Chromium-based version)
Mozilla Firefox (latest Extended Support Release)
Google Chrome
Internet Explorer 11

We will update you once we support safari browser.
