### ISSUE TITLE
Digital Twin Manager :  Unable to select all entries in the page where pagination is available.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#2]
In Asset Overview page, When there are more than 10 entries in page and user selects "select all" checkbox on top, there is an option that says "select n entries". [n in total number of assets]. But when clicked on this, it does not select all entries.

This is the case for all pages with Pagination option.

**Comment by GalaxyJadar** [comment]
“Select n entries” functionality i.e., displayed on the banner is removed in the current build. This change is available in the latest uploaded DTM version
