### ISSUE TITLE
Add button in not accessible in complex property section

### ISSUE THREAD

**Issue by rahultalreja11** [SoftwareAG/cumulocity-digital-twin-manager#20]
Screenshot added
![Screenshot (1)](https://user-images.githubusercontent.com/14932382/186174280-df41bf1d-d136-4625-a164-1bc4d1560712.png)
.

Screen recording of the same is visible in this file: [screen-recording(1).webm](https://user-images.githubusercontent.com/14932382/186628139-45ff77c3-e0c9-477f-a2e2-945c1d32d97c.webm)

**Comment by pavanshivajirao** [comment]
Already fixed and will be available in the latest build.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
