### ISSUE TITLE
Asset Properties section keeps loading and doesn't display any data

### ISSUE THREAD

**Issue by rahultalreja11** [SoftwareAG/cumulocity-digital-twin-manager#21]
Asset Properties section keeps loading and doesn't display any data

Occurred after adding a 3rd complex property with 3 items.
![Screenshot (2)](https://user-images.githubusercontent.com/14932382/186192347-847db6fb-f632-4389-9b50-67a2f7b4cf48.png)

[screen-recording.webm](https://user-images.githubusercontent.com/14932382/186627426-0f7eb0f1-7856-4fb3-929c-c03d23d929b5.webm)

**Comment by pavanshivajirao** [comment]
Already fixed and will be available in the latest build.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
