### ISSUE TITLE
Add Child Asset button on subasset page results in blank section

### ISSUE THREAD

**Issue by rahultalreja11** [SoftwareAG/cumulocity-digital-twin-manager#22]
Screenshot added
![image](https://user-images.githubusercontent.com/14932382/186379574-5550f846-1388-4bc6-9a67-5c5b3e61ffd9.png)

**Comment by pavanshivajirao** [comment]
Designed that way for now. Need to check if it is possible to disable the button.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
