### ISSUE TITLE
Unable to edit and save existing Asset Property type-complex

### ISSUE THREAD

**Issue by rahultalreja11** [SoftwareAG/cumulocity-digital-twin-manager#23]
Steps to reproduce
1) Create asset property with type complex property and add 3 key-value pairs
2) Save the asset property
3) Assign the property to an asset
4) Navigate to asset page and submit details for the respective asset and save
5) Now Edit the property and add 4 the key to same asset property, and it will not provide option to save it

Video displaying the occurrence of the issue

https://user-images.githubusercontent.com/14932382/186619517-3bf69f97-8a31-4178-a4cf-fccf633696c2.mp4

**Comment by pavanshivajirao** [comment]
Already fixed and will be available in the latest build.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
