### ISSUE TITLE
Recent Version

### ISSUE THREAD

**Issue by itsyitsy** [SoftwareAG/cumulocity-digital-twin-manager#24]
Hello Digital Twin Team,

Is there any more recent version of the Digitial Twin Manager that you can upload?

**Comment by srinath0707** [comment]
Hello,

It will be available by 16-Sep-2022

**Comment by itsyitsy** [comment]
Thanks @srinath0707 for the reply.
We will give the new version a try.
Is there any description what the Microservice does?

**Comment by srinath0707** [comment]
Hi,
We are currently updating the Readme file. It will have the required information.

Thanks

**Comment by GalaxyJadar** [comment]
Uploaded and verified the new version.
