### ISSUE TITLE
Import Asset is still missing after assigning Digital Twin permissions to user

### ISSUE THREAD

**Issue by scott-guenther-saggs** [SoftwareAG/cumulocity-digital-twin-manager#26]
Added Digital twin Admin permission to existing Global Role assigned to my profile.  Import Assets link on the assets page is still missing.

**Comment by rahultalreja11** [comment]
I faced the same problem initially. This is how I was able to get it working.

1) Verify if your current UI version is 10.15 or above. 

2) Verify if the microservice has been installed as mentioned on [Link](https://github.com/SoftwareAG/cumulocity-digital-twin-manager#for-installation-of-microservice)

3) Verify is the DTM has been enabled for your role.

![Microservice](https://user-images.githubusercontent.com/14932382/195101262-fac0d1a5-0d8f-4408-ade8-0037a4563ef8.gif)

**Comment by scott-guenther-saggs** [comment]
@rahultalreja11, @pavanshivajirao, I have loaded the latest assets (build 312) for the ui and ms. Confirmed ms is subscribed.  I assigned the Digital twin permission to the admins role and the user has the admins role assigned.   The Import assets link still is not being displayed.

**Comment by scott-guenther-saggs** [comment]
Yes, I have a meeting scheduled with Rahul today @ 11am EDT.  @rahultalreja11 can forward the link to the meeting if needed.

**Comment by pavanshivajirao** [comment]
Can this be closed ?

**Comment by pavanshivajirao** [comment]
Closing this as the issues is resolved as confirmed by @rahultalreja11
