### ISSUE TITLE
Digital Twin Manager : Validations missing in Assets section.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#3]
In the Digital Twin Manager application, under Assets section, validations are missing for the below scenarios :

1. User is able to create 2 hierarchies with same asset name, this should not be allowed.

2. In Assets page, able to create Asset with blank name. This should not be allowed.

3. Asset names donot have any upper limit on the maximum number of characters.

**Comment by spau6** [comment]
Refer https://itrac.eur.ad.sag/browse/CTM-42 for details
