### ISSUE TITLE
Properties Tab getting displayed even when no properties are assigned

### ISSUE THREAD

**Issue by rahultsag** [SoftwareAG/cumulocity-digital-twin-manager#30]
Found on dtm-ui-1015.0.0.312 that Properties Tab getting displayed even when no properties are assigned
Tried with 2 separate tenants with different hierarchy

![image](https://user-images.githubusercontent.com/116082992/198062779-aa519518-47c2-45a9-ad65-b482028b7b0e.png)

![image](https://user-images.githubusercontent.com/116082992/198063186-434addde-b7a4-4c64-84fd-3ac88dae7aac.png)

**Comment by pavanshivajirao** [comment]
@rahultsag This is how it is implemented. So, it is not a defect. But if you think we should not display the properties section when there are no properties, then we can check and work on this enhancement.

**Comment by Vagdevi1998** [comment]
This has been fixed in the build 1016.0.0.364. Hence closing the issue.
![image](https://user-images.githubusercontent.com/107403521/211272238-c42f7af1-af49-4ad0-9c78-575ed40ec304.png)
