### ISSUE TITLE
Unable to upload .PNG images but .png is working

### ISSUE THREAD

**Issue by rahultsag** [SoftwareAG/cumulocity-digital-twin-manager#31]
Even when both the file types .PNG and .png are allowed, the platform gives error when uploading a .PNG file

Renaming the file extension works immediately 

![image](https://user-images.githubusercontent.com/116082992/198071756-e5ad7213-f5dc-4075-b8f0-4dd57794b80a.png)

**Comment by dchc01** [comment]
The problem has been fixed and confirmed in the latest build (1019.1.2). @rahultsag Can I close the issue if it's working for you now?

**Comment by rahultsag** [comment]
![ Cumulocity - Digital twin manager 2024-02-02 10-19-44](https://github.com/SoftwareAG/cumulocity-digital-twin-manager/assets/116082992/da26dce0-d557-4781-9eaa-b84e17a1b280)
able to upload .PNG file now
