### ISSUE TITLE
Order of Hierarchy in Navigation doesn't seem to be correct

### ISSUE THREAD

**Issue by rahultsag** [SoftwareAG/cumulocity-digital-twin-manager#33]
Order of Hierarchy in Navigation doesn't seem to be correct

Example: Press Shop Asset is at the beginning of the hierarchy but is being displayed at the last in navigation.

![image](https://user-images.githubusercontent.com/116082992/200522179-d0152b5d-e7a0-4a04-879a-b7870f1a1649.png)

**Comment by dchc01** [comment]
@rahultsag It is displayed as per alphabetical order, so it is not a bug.

**Comment by dchc01** [comment]
With the addition of the Asset tree view, assets are no longer listed in the left navigation from the 1017 release onwards. @rahultsag  Can I close this issue?

**Comment by rahultsag** [comment]
Yes.
