### ISSUE TITLE
Ordering of complex asset properties

### ISSUE THREAD

**Issue by mbie-sag** [SoftwareAG/cumulocity-digital-twin-manager#35]
It would be nice to have the possibility to order complex properties after creation.

**Comment by srinath0707** [comment]
Hi Marco,

Please let us know few use cases where it will be useful. It will be helpful for us to prioritize.

**Comment by dchc01** [comment]
Ordered key-value pairs in complex properties are now implemented in the 1019.1.1 release. Therefore, I am closing this issue.

**Comment by Vagdevi1998** [comment]
When creating a complex property, an optional field for order is provided, allowing users to specify the order in which keys should appear. The order field accepts a comma-separated list of keys as input.

Default Behavior:
If the user omits the order input while creating the complex property, the system automatically considers the order in which the properties are added. In this case, the properties will be arranged in the order they were included.

Partial Input Handling:
When users partially enter keys in the order field, the system intelligently completes the order by adding the remaining set of properties automatically at the end. This feature ensures flexibility and convenience for users who may not want to specify the complete order manually.
