### ISSUE TITLE
Unable to add child device to an asset

### ISSUE THREAD

**Issue by scharri** [SoftwareAG/cumulocity-digital-twin-manager#36]
I would like to add child devices to an asset but I'm unable to do so:

![image](https://user-images.githubusercontent.com/4233022/204297869-7bd5c70d-a277-46f4-aafb-62d0196188a0.png)

I would expect to see the show child button to be able to add child devices to an asset.

Information:
All my child devices are not marked as c8y_device because they don't need device management functionalities.
DTM version: 1015.0.0.318

**Comment by mbie-sag** [comment]
Hi @scharri,
to make the UI of Cumulocity aware of the in you case generic Managed Object, you either have to add the device or asset fragment to it as the UIs filter for this. If this would not be the case you would have a vast number of objects showing up, which would not make any sense.

BR
Marco
