### ISSUE TITLE
Unable to subscribe to microservice via file dtm-ms-1016.0.0.561.zip

### ISSUE THREAD

**Issue by rahultsag** [SoftwareAG/cumulocity-digital-twin-manager#37]
Unable to subscribe to microservice via file dtm-ms-1016.0.0.561.zip

Tenant Type: New tenant without any application or microservices related to DTM

Error Message: Push failed on image : An error has occurred.

Error Screenshot: 
![image](https://user-images.githubusercontent.com/116082992/211281949-7d4c8e50-b368-4cf2-9bfd-a91eec853b75.png)

![image](https://user-images.githubusercontent.com/116082992/211283533-381de6d4-c12e-4378-b8a4-8de97ebb30b8.png)

**Comment by spau6** [comment]
It was a issue with the latest(10.17) tenant where none of the microservices were getting uploaded and was trowing the same error as attached.
This issue is fixed please reupload the artifacts. I have tested from my end and it working as expected.
