### ISSUE TITLE
Custom properties reordering doesn't seems to be working as expected

### ISSUE THREAD

**Issue by rahultsag** [SoftwareAG/cumulocity-digital-twin-manager#38]
Custom properties reordering doesn't seems to be working as expected

Backend: 1015.0.218
UI: 1015.0.79

Screenshot
![image](https://user-images.githubusercontent.com/116082992/216648467-8e7dc07d-e9d7-4242-9852-bf0e5c3d1cbc.png)

**Comment by pavanshivajirao** [comment]
Hi Rahul, 
could you please add more details on the steps to reproduce/expected behavior ?

**Comment by janhommes** [comment]
The sorting was introduced in Cockpit only in 10.16, in 10.15 it wasn't possible.

**Comment by rahultsag** [comment]
verified that this feature is working in 10.16.

**Comment by pavanshivajirao** [comment]
Can we please close this issue @rahultsag  ?
