### ISSUE TITLE
DTM: Assets: Issues observed in custom properties section under subassets page.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#4]
1) Create an asset type with the simple custom property. Navigate to Assets page and create an asset hierarchy. Now navigate to subassets page, the custom properties of an asset is being displayed on right side of the screen.

Behavior observed:  Only the properties value has been shown, which is not very clear for the user. 
Expected behavior: Properties value should be shown along with the name.

2) Follow the steps mentioned in the above issue. Instead of simple custom property, create complex property.

Behavior observed: The property key is being shown as a property header under custom properties which is incorrect. 
Expected behavior: The property label should be shown as a header.

3) If user deletes a property from the asset type which is used in an existing asset hierarchy and add another then the property which is added newly is not getting loaded under custom properties section in subassets screen.

**Comment by GalaxyJadar** [comment]
Fix is available in the latest uploaded DTM version
