### ISSUE TITLE
DTM : Select all devices link does not work as expected.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#7]
In DTM application, in any of the pages where a check box is displayed against the rows, user has an option to select all the rows using Select-all at top.

On click on this "Select all" icon, another link gets displayed asking if user wants to select all the rows in all the page. But on click of the option, the rows of other pages are not selected.

Either this option needs to be removed or the functionality has to work so that all rows gets selected.

Another issue observed is that in "Assign devices" page, (lazy loading is implemented here) on click of Select all option, only 20 devices or the number of devices loaded currently gets selected, which is not the expected behavior. Ideally on Select all, all the rows will have to get selected.

**Comment by spau6** [comment]
Refer https://itrac.eur.ad.sag/browse/CTM-35 for details
