### ISSUE TITLE
DTM: Property library: Issues observed in Add new property screen.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#8]
Issues are mentioned below,

1) When user is creating a custom property, and default value is already filled, then the moment user clicks on Max length check box, empty validation error is displayed for default value. It should be displayed only if the default value does not conform to the max length of characters.

2) When creating a custom property of type text, in minimum length field, user is able to reduce the value to lesser than 0 using the decrement icon. This should not be allowed.

3) If user selects type as a text and configures min & max length, it is observed that if they don’t provide value as per the condition then error message is being displayed only for min length not for max. Though user can’t provide text beyond max length.

4) Validation issue when creating custom property of type number. In case user provides a 2 digit number as maximum limit and enters a default value greater than that, then in validation message only the first digit is seen.

5) Validation for Key field is missing in the complex custom property. It accepts space/special characters as valid input.

**Comment by spau6** [comment]
Refer https://itrac.eur.ad.sag/browse/CTM-34 for details
