### ISSUE TITLE
DTM : Assets : In Assets page the total asset count at bottom is not getting displayed.

### ISSUE THREAD

**Issue by nupadhyaya** [SoftwareAG/cumulocity-digital-twin-manager#9]
In DTM application the beow issues are observed :

- The asset count displayed at the bottom is not correct. Instead of count, a variable gets displayed which is not the expected behavior.
- In Assets page, the no filter label and the help icon for filters have to be removed as there is no filter option in this page.
- Currently in all the screens where configure column is available, user is able to deselect all columns which should be restricted.
- When creating an asset, for next button to be enabled, user has to click outside the form. This is the behavior for all forms.
- If there are more than 20 Assets, then it does not get displayed on the grid. User is able to see the same in left pane though.

**Comment by spau6** [comment]
Refer https://itrac.eur.ad.sag/browse/CTM-33 for more details
